replicaCount: 1

image:
  repository: 199837183662.dkr.ecr.us-east-2.amazonaws.com/scos/mmtpa-adapter
  pullPolicy: Always
  tag: latest

nameOverride: ""
fullnameOverride: ""

service:
  type: ClusterIP
  port: 80

resources:
  limits:
    cpu: 1
    memory: 2Gi
  requests:
    cpu: 1
    memory: 2Gi


nodeSelector: {}

tolerations: []

affinity: {}
